### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by nekoniyah** [Qu4k3/disboard-api#12]
No Game No Life
That's nice

But is it terminated? I can't access to api.disboard.team and i'm curious why the title of disboard.team is a esport thing, then if it's a bot I can't find the invite link in the website.

(btw I found this website by searching on google "disboard api", for disboard.org)

**Comment by Qu4k3** [comment]
Thanks for reaching to me @KinyaDev,

Yeah, Disboard was a Mario Kart Competitive E-Sports Team back in the days (2018) ([Check link](https://www.mariokartcentral.com/mkc/registry/teams/5))

And nearly being a Counter-Strike thing too!

The API was hosted on Heroku... but just checked and `Heroku-18 stack` were it was deployed reached end-of-life on April 30th, 2023.

The bot was developed for only use in Disboard's private Discord server, but used to be a thing :)

I am curious too that the website was that much relevant in Google indexation being down for that long time.

**Comment by nekoniyah** [comment]
Okay 😂 good to see that there was an history behind this, alright good luck (idk why I want just to know more about you)

**Comment by Qu4k3** [comment]
Here you can find all things related to that project (I'm proud of the documentation 😊) https://docs.disboard.team/

And here was the preview of the website: https://dev.disboard.team/ (now broken due to API and image hosting down)

PD: closing this issue, you can find me on Discord (quake654) if needed, thanks :)
